version: 2
builds:
  - skip: true
release:
  draft: true
  use_existing_draft: true
  mode: replace
changelog:
    sort: asc
    use: github
    groups:
      - title: Features
        regexp: "^feat:"
        order: 0
      - title: Bug Fixes
        regexp: "^fix:"
        order: 1
      - title: CI
        regexp: "^ci:"
        order: 2
      - title: Docs
        regexp: "^docs:"
        order: 3
    filters:
        exclude:
        - "^test:"
        - "^chore:"
        - "^refactor:"
        - "^style:"
        - "^perf:"
        - "^build:"
        - "^revert:"
        - "^deps:"
