version: 2
builds:
  - skip: true
release:
  draft: true
  use_existing_draft: true
  mode: replace
  header: |
    ###### REMOVE THIS HEADER BEFORE RELEASE ##################
    ## Release Checklist
    ### Draft Checklist
    - [ ] Tests from last nightly build have passed and are stable.
    - [ ] Release notes below have been reviewed and edited as needed.
    - [ ] Binaries from each distro have been built and are attached to the release.
      - [ ] nrdot-collector-host
      - [ ] nrdot-collector-k8s
    - [ ] Docker images for each distro have been published to docker hub
      - [ ] [nrdot-collector-host](https://hub.docker.com/repository/docker/newrelic/nrdot-collector-host/tags) image published and tagged
      - [ ] [nrdot-collector-k8s](https://hub.docker.com/repository/docker/newrelic/nrdot-collector-k8s/tags) image published and tagged
    - [ ] Docker images for each distro have been published to New Relic registry
    - [ ] Slack notifications have been sent to appropriate channels
    ### Release Checklist
    - [ ] Release has been published
    - [ ] Docker images for each distro have been tagged as latest
      - [ ] [nrdot-collector-host](https://hub.docker.com/repository/docker/newrelic/nrdot-collector-host/tags) version {{ .Version }} tagged as latest
      - [ ] [nrdot-collector-k8s](https://hub.docker.com/repository/docker/newrelic/nrdot-collector-k8s/tags) version {{ .Version }} tagged as latest
    ###### REMOVE THIS HEADER BEFORE RELEASE ##################

changelog:
  sort: asc
  use: github
  format: "{{ .Message }} ({{ with .AuthorUsername }}@{{ . }}{{ else }}{{ .AuthorName }} <{{ .AuthorEmail }}>{{ end }})"
  groups:
    - title: Features
      regexp: "^.*(feat:|feat\\/|feat(\\([^\\)]*\\)):).*"
      order: 0
    - title: Bug Fixes
      regexp: "^.*(fix:|fix\\/|fix(\\([^\\)]*\\)):).*"
      order: 1
    - title: Docs
      regexp: "^.*(docs:|docs\\/|docs(\\([^\\)]*\\)):).*"
      order: 2
  filters:
    exclude:
      - "^ci"
      - "^test"
      - "^chore"
      - "^refactor"
      - "^style"
      - "^perf"
      - "^build"
      - "^revert"
      - "^deps"
  